# $FreeBSD: head/devel/riscv64-binutils/Makefile 458356 2018-01-07 16:30:06Z lwhsu $

COMMENT=	GNU binutils for RISC-V cross-development
PKGNAMEPREFIX=	riscv64-
PLIST=	${.CURDIR}/pkg-plist

MASTERDIR=	${.CURDIR}/../binutils
OPTIONS_DEFAULT=	STATIC

.include "${MASTERDIR}/Makefile"
